##########################################################################
# azure-pipelines.com.yml
# github.com/sapiderman/seed-nodejs
# https://docs.microsoft.com/azure/devops/pipelines/languages/go
#########################################################################
name: $(Build.DefinitionName) - $(Date:yyyMMdd) Build $(BuildID)


trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: templates
      name: sapiderman/pipeline
      type: github
      endpoint: sapiderman

stages:
  - stage: Build_and_Test

    jobs:
      - job: pull_request
        displayName: 'Build and Test for Pull Request'
        condition: always() #and(succeeded(), in(variables['Build.Reason'], 'Manual', 'PullRequest'))
        timeoutInMinutes: 30

        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '14.x'
          displayName: 'Install Node.js'

        - template: azure/node/doBuild.yml@templates
        - template: azure/node/doTest.yml@templates
